config/routes.rb
Rails.application.routes.draw do
  get 'viewings/create'
  get 'viewings/update'
  get 'films/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'pages#home'

  resources :users do
    get 'films', to: 'films#user_films', on: :member
    post 'reset_viewings', to: 'users#reset_viewings'
    member do
      get 'film_list', to: 'users#film_list'
    end
   
  end

  get 'films/compare/:usernames', to: 'films#compare', as: 'compare_films'

  resources :films do
    get 'compare/:usernames', to: 'films#compare', on: :collection, as: 'compare_users'
  end

  resources :viewings do
    collection do
      post 'create_or_update'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/film.rb
class Film < ApplicationRecord
    has_many :viewings, dependent: :destroy
    has_many :users, through: :viewings

    after_create_commit { broadcast_prepend_to :films }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :viewings, dependent: :destroy
    has_many :films, through: :viewings
    validates :username, uniqueness: true

    def seen?(film)
        viewings.exists?(film: film)
    end

end

app/models/viewing.rb
class Viewing < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
# app/controllers/films_controller.rb

class FilmsController < ApplicationController
  helper_method :styling_for_user_film # Add this line to make the helper method accessible in the view

  def index
    if params[:user_id].present?
      @user = User.find(params[:user_id])
    end
    @all_films = Film.all.order(created_at: :desc)
  end
  
  def compare
    # Fetch users from params
    usernames = params[:usernames].split(',')
    @users = User.where(username: usernames)

    # Fetch all films
    @all_films = Film.all

    # Prepare films seen by each user
    @films_seen_by_users = {}
    @users.each do |user|
      @films_seen_by_users[user.id] = user.viewings.pluck(:film_id)
    end

    # Prepare films unseen by any user
    @unseen_films = @all_films.reject do |film|
      @films_seen_by_users.any? { |user_id, seen_films| seen_films.include?(film.id) }
    end
  end

  def compare_index
    # This action is used to render the compare_index view
  end

  def create
    @film = Film.new(film_params)
    
    if @film.save
      redirect_to @film, notice: "Film was successfully created"
    else
      render :new, notice: @film.errors.full_messages
    end
  end

  def show
    @film = Film.find(params[:id])
  end


  def user_films
    @user = User.find(params[:id])
    @all_films = Film.all
  end

  def new
    @film = Film.new
  end

  def film_params
    params.require(:film).permit(:title, :director, :release_date)
  end


  private

  def styling_for_user_film(user, film)
    if @unseen_films.include?(film)
      'background-color: #fffde03d;'
    elsif @films_seen_by_users[user.id].include?(film.id)
      'text-decoration: line-through;'
    else
      'font-weight: bold;'
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      # Your controller logic (if needed)
      @users = User.first(5)
      @usernames = @users.first(3).pluck(:username)
      @usernames_string = @users.first(3).pluck(:username).join(',')
    end
  end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb

class UsersController < ApplicationController
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      unless @user.username.present?
        first_name, last_name = user_params[:name].split(' ')
        @user.username = "#{first_name.downcase}#{last_name[0].downcase}"
      end

      if @user.save
        redirect_to @user, notice: 'User was successfully created.'
      else
        render :new, notice: @user.errors.full_messages
      end
    end
  
    def show
      @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :username)
    end
      

    def film_list
      @user = User.find(params[:id])
      @all_films = Film.all

      respond_to do |format|
        format.html # Render HTML view
        format.turbo_stream # Respond to Turbo Streams
      end
    end

    def reset_viewings
    
      @user = User.find(params[:user_id])
      viewings = Viewing.where(user: @user)
      # debugger
      viewings.each do |viewing|
        viewing.destroy
      end
    end
  end
  

app/controllers/viewings_controller.rb
class ViewingsController < ApplicationController
  include ActionView::RecordIdentifier
    def create
        respond_to do |format|
          format.html { redirect_to film_list_user_path(@user), notice: 'Movie marked as viewed.' }
          format.turbo_stream { render turbo_stream: turbo_stream.replace("film_#{film.id}", partial: 'film_button', locals: { film: film, user: @user }) }
        end
    end

  def update
  end

  def destroy
  
  end

  def create_or_update
    @film = Film.find(params[:film_id])
    @user = User.find(params[:user_id])
  
    # Check if the user has seen the film
    if @user.seen?(@film)
      # If the user has seen the film, update the existing viewing
      @viewing = @user.viewings.find_by(film: @film)
    else
      # If the user hasn't seen the film, create a new viewing
      @viewing = Viewing.new(user: @user, film: @film)
    end
  
    # Save the viewing
    if @viewing.save
      respond_to do |format|
        format.turbo_stream 
        format.html { redirect_to film_list_path } # Adjust the redirect path if needed
        format.json { render json: { status: 'success' } } # Add this line
      end
    else
      # Handle errors if saving fails
      # ...
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/viewings_helper.rb
module ViewingsHelper
end

app/views/films/_film.html.erb
<% if @user.present? %>
  <li>
    <div id="<%= "film_#{film.id}" %>" class="film-button <%= 'film-seen' if @user.seen?(film) %>"
         data-controller="viewings"
         data-action="click->viewings#createAndView"
         data-url="<%= create_or_update_viewings_path(film_id: film.id, user_id: @user.id) %>"
         data-film-id="<%= film.id %>">
      <%= "#{film.title} (#{film.release_date.year})" %>
    </div>
  </li>
<% else %>
  <li>
    <%= link_to "#{film.title} (#{film.release_date.year})", film_path(film), class: 'film-button' %>
  </li>
<% end %>

app/views/films/compare.html.erb
<h2>Compare Film Lists</h2>

<div class="unseen-films">
  <h3>Films all users haven't seen</h3>
  <% @unseen_films.each do |film| %>
    <p><%= film.title %></p>
  <% end %>
</div>

<div class="comparison-holder">
  <div class="comparison">
    <% @users.each do |user| %>
      <div class="user-container">
        <h2><%= user.name %>'s Film List</h2>
        <div class="user-films">
          <% @all_films.each do |film| %>
            <p style="<%= styling_for_user_film(user, film) %>">
              <%= film.title %>
            </p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/films/compare_index.html.erb
<h1>Compare Users</h1>

<%= form_tag(compare_films_path, method: :get) do %>
  <div class="user-list">
    <% User.all.each do |user| %>
      <label>
        <%= check_box_tag "usernames[]", user.username %>
        <%= link_to user.username, user_path(user) %>
      </label>
    <% end %>
  </div>

  <%= submit_tag 'Compare', class: 'compare-button' %>
<% end %>

app/views/films/index.html.erb
<h1>All Films</h1>

<%= turbo_stream_from :films %>
<ul>
  <%= turbo_frame_tag :films do %>
    <%= render @all_films %>
  <% end %>
</ul>

<%= link_to 'New Film', new_film_path, class: 'film-button' %>

app/views/films/new.html.erb
<h1>New Film</h1>

<div class="film-form">
  <%= form_for @film do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :director %>
      <%= f.text_field :director %>
    </div>

    <div>
      <%= f.label :release_date %>
      <%= f.date_field :release_date %>
    </div>


    <div>
      <%= f.submit "Create Film", class: "registerbtn" %>
    </div>
  <% end %>


  <% if @film.errors.any? %>
    <div>
      <h2>Errors:</h2>
      <ul>
        <% @film.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/films/show.html.erb
<h1><%= @film.title %></h1>

<p><strong>Director:</strong> <%= @film.director %></p>
<p><strong>Release Date:</strong> <%= @film.release_date %></p>
<!-- Add other film details as needed -->

<%= link_to 'Back to Films', films_path %>

app/views/films/user_films.html.erb
<h1><%= @user.name %>'s Film List</h1>

<% @all_films.each do |film| %>
  <p style="<%= @user.viewings.find_by(film: film) ? 'text-decoration: line-through;' : 'font-weight: bold;' %>">
    <%= film.title %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmpicker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage">
  <ul>
    <li><%= link_to 'View Films', films_path %></li>
    <li><%= link_to 'View Users', users_path %></li>
    <li><%= link_to 'Example Comparison', compare_films_path(usernames: @usernames_string), class: 'button' %></li>
  </ul>
</div>

app/views/shared/_footer.html.erb
<footer style="text-align: center;">
  Copyright <%= Time.now.year %> Phil W.
</footer>

app/views/shared/_header.html.erb
<header>
  <h1><%= link_to 'Film Finder', root_path, class: 'header-link' %></h1>
  <h2>A Place to Find Films</h2>
</header>

app/views/users/film_list.html.erb
<h3>Film List for <%= link_to @user.username, user_path(@user) %> (<%= @user.name%>)</h3>

<%= turbo_stream_from :films %>
<ul>
  <%= turbo_frame_tag :films do %>
    <%= render @all_films %>
  <% end %>
</ul>

app/views/users/index.html.erb
<h3>Users List</h3>

<ul>
  <% @users.each do |user| %>
  <div class="users-list">
    <li>
      <%= link_to user.name, film_list_user_path(user) %>
    </li>
  </div>
  <% end %>
</ul>

<ul>
  <div class="users-list">
    <li><%= link_to "Add a new user", new_user_path %></li>
  </div>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<div class="user-form">
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div>
      <%= f.submit "Create User", class: "registerbtn" %>
    </div>
  <% end %>


  <% if @user.errors.any? %>
    <div>
      <h2>Errors:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p>Email: <%= @user.email %></p>
<p>Username: <%= @user.username %></p>

<%= link_to 'View Films', film_list_user_path(@user) %>
<%= link_to 'Compare with Other Users', compare_users_films_path(usernames: [@user.username, User.first.username, User.second.username].join(',')) %>

<hr>
<%= button_to 'Reset Viewings', user_reset_viewings_path(@user), method: :post %>

app/views/viewings/_viewing.html.erb
<turbo-stream action="replace" target="viewing_<%= viewing.id %>">
  <%= render partial: 'viewings/viewing', locals: { viewing: viewing } %>
</turbo-stream>

app/views/viewings/create_or_update.turbo_stream.erb
<%= turbo_stream.replace "film_#{@film.id}", partial: 'films/film', locals: { film: @film, user: @user } %>